site_name: llm-dataset-converter examples
site_url: https://waikato-llm.github.io/llm-dataset-converter-examples/
repo_url: https://github.com/waikato-llm/llm-dataset-converter-examples
edit_uri: edit/master/docs/
site_description: Examples for using the llm-dataset-converter libraries
theme:
    name: material
markdown_extensions:
    - toc:
          baselevel: 2
          permalink: "#"
    - attr_list
plugins:
    - search
nav:
    - Home: index.md
    - Core library:
        - Downloader usage: downloaders.md
        - General usage: general_usage.md
        - Processing multiple files: processing_multiple_files.md
        - Locating files: locating_files.md
        - Compression: compression.md
        - Filter usage: filters.md
        - Docker usage: docker.md
    - Additional libraries:
        - MS Word (doc): doc.md
        - MS Word (docx): docx.md
        - Faster whisper: faster_whisper.md
        - gitingest: gitingest.md
        - Google: google.md
        - HTML: html.md
        - OpenAI: openai.md
        - PDF: pdf.md
        - TinT: tint.md
